# Composition

一套好的工具

* 包含简单用途的项目。 例如锤子或扳手
* 可以一起用于复杂的任务。 例如，我们可以用锤子打一个扳手，松开一个紧的螺母

我们称之为“一起使用”的组合


In [1]:
# We reuse the following binary operators from last time
def add(x, y):
    return x + y

def mul(x, y):
    return x * y

def lesser(x, y):
    if x < y:
        return x
    else:
        return y

def greater(x, y):
    if x > y:
        return x
    else:
        return y

In [3]:
# Also consider the following higher order functions
map
from functools import reduce
from toolz import accumulate

在本节中，我们将组成具有更高阶函数的二元运算符。

首先我们需要介绍一下`accumulate`，reduce的兄弟函数，以及`map`的多重参数行为。 我们将从`accumulate`开始。


In [9]:
# When showing off numpy we used the cumulative sum method

import numpy as np
X = np.arange(20)
print(X)

X[X>=10].cumsum()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145], dtype=int32)

In [10]:
# Accumulate is a general version of this

data = range(10, 20)

list(accumulate(add, data))

[10, 21, 33, 46, 60, 75, 91, 108, 126, 145]

理想情况下，这些工具一起涵盖大部分相关任务

In [11]:
X[X>=10].cumprod()

array([       10,       110,      1320,     17160,    240240,   3603600,
        57657600, 980179200, 463356416, 213837312], dtype=int32)

In [14]:
print(list(data))
list(accumulate(mul, data))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


[10,
 110,
 1320,
 17160,
 240240,
 3603600,
 57657600,
 980179200,
 17643225600,
 335221286400]

## 有效工具和钻头

考虑通常被称为电钻的设备。 这个装置本身是无用的，只是旋转一个空的插座。 更准确地说，这是一个“动力微调”或“自动扭矩”

结合几个比特之一，但自动torquer承担各种角色。

此外，这些相同的钻头可以用在其他扭力扳手上，如套筒扳手或棘轮螺丝刀。

toolz就是一组相对紧凑的工具集，从中可以获得各种各样的解决方案。


我们还需要展示map如何在二元运算符上运行。

### Power functions

我们已经看到了三种类似的功能，比如电钻，map，reduce和accumulate。 他们每个人都可以使用二元运算符。


In [16]:
data1 = [1, 2, 3, 4, 5]
data2 = [10, 20, 30, 40, 50]
list(map(add, data1, data2))

[11, 22, 33, 44, 55]

In [17]:
reduce(lesser, [5, 3, 2, 7, 3], 999999999)

2

In [18]:
list(accumulate(lesser, [5, 3, 2, 7, 3]))

[5, 3, 2, 2, 2]

In [20]:
list(map(lesser, [5, 3, 2, 7, 3], [1, 9, 2, 6, 6]))  # Pairwise lesser across the two lists

[1, 3, 2, 6, 3]

所以现在我们有四个二元运算符

    add, mul, lesser, greater
    
还有三个可以利用二元运算符的高阶函数

    map, reduce, accumulate
    
而且我们可以有意义地把它们中的任何一对合并

## Exercise

创建一个新的二元运算符`longer`，它返回两个元素中较长的一个


In [11]:
def longer(a, b):
    ...
    
assert longer('cat', 'mouse') == 'mouse'  # because cat is of length 3 and mouse is of length 5

SyntaxError: invalid syntax (<ipython-input-11-663766df1d5d>, line 2)

使用这个二元运算符与`reduce`，`accumulate`和`map`一起计算以下内容

最长的单词:

longest word, the longest word over time, and the longest between pairs

In [12]:
# Use reduce to find the longest word

animals = ['cat', 'mouse', 'lion', 'goose', 'giraffe', 'mule']

In [13]:
# Use accumulate to track the longest word over time.
# This should be a list where the first element is 'cat', the last is 'giraffe', 
# and each intermediate element is the longest word up to that point


In [14]:
# Use map to create a list of the pairwise longest among the following two lists
animals = ['cat', 'mouse', 'lion', 'goose', 'giraffe', 'mule']
fruits  = ['apple', 'orange', 'banana', 'date', 'grape', 'strawberry']



## Recap

功能标准库涵盖了各种各样的具有少量功能的应用程序。 它通过精心设计的高阶功能来达到这个目的。 通过设计，这些功能是高度可组合的，也就是说，它们可以一起使用。

这种构成原则扩展了这个特定的设计。

